spring:
  application:
    name: store-app
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: pandu

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  currencies: USD,EUR,INR
  timeout: 1000

server:
  port: 8081