spring:
  application:
    name: store-app
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: pandu
  jpa:
    show-sql: true

server:
  port: 8081